const API = (() => {
  const configured = window.FARMLINK_API_URL?.trim();
  if (configured) return configured.replace(/\/$/, '') + '/api';

  const localHosts = new Set(['localhost', '127.0.0.1']);
  if (localHosts.has(window.location.hostname)) return 'http://localhost:8000/api';

  return 'https://farmlinkdistribution.onrender.com/api';
})();
let token=localStorage.getItem('farmlink_token')||'';
let currentUser=null;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const toast=(m,ok=true)=>{const t=$('#toast');t.textContent=m;t.style.background=ok?'#0b6b49':'#a62b2b';t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3500)};
const authHeaders=()=>({'Content-Type':'application/json','Authorization':`Bearer ${token}`});
async function api(path,opts={}){const r=await fetch(API+path,{...opts,headers:{...authHeaders(),...(opts.headers||{})}});if(r.status===401){logout();throw new Error('Session expired')}const d=r.status===204?null:await r.json();if(!r.ok)throw new Error(d?.detail||'Request failed');return d}
function logout(){localStorage.removeItem('farmlink_token');token='';currentUser=null;$('#app').classList.add('hidden');$('#loginScreen').classList.remove('hidden')}
$('#logout').onclick=logout;
$('#loginForm').onsubmit=async e=>{e.preventDefault();$('#loginError').textContent='';try{const r=await fetch(API+'/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:$('#loginEmail').value,password:$('#loginPassword').value})});const d=await r.json();if(!r.ok)throw new Error(d.detail||'Sign-in failed');token=d.access_token;localStorage.setItem('farmlink_token',token);currentUser=d.user;start()}catch(err){$('#loginError').textContent=err.message}};
async function start(){try{currentUser=currentUser||await api('/auth/me');$('#loginScreen').classList.add('hidden');$('#app').classList.remove('hidden');$('#sideName').textContent=currentUser.full_name;$('#sideRole').textContent=currentUser.job_title;$('#usersNav').style.display=currentUser.role==='CEO'?'block':'none';$('#today').textContent=new Intl.DateTimeFormat('en-ZA',{dateStyle:'full'}).format(new Date());await showView('dashboard')}catch{logout()}}
$$('#nav button').forEach(b=>b.onclick=()=>showView(b.dataset.view));$('#refresh').onclick=()=>showView($('.view.active').id);
async function showView(name){$$('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===name));$$('.view').forEach(v=>v.classList.toggle('active',v.id===name));const titles={dashboard:'Operations overview',farmers:'Farmer applications',buyers:'Business buyers',orders:'Bulk orders',memberships:'Memberships and marketing',payments:'Payments',users:'Administrator management',audit:'Audit trail'};$('#pageTitle').textContent=titles[name]||name;if(name==='dashboard')return loadDashboard();if(['farmers','buyers','orders','memberships'].includes(name))return loadResource(name);if(name==='payments')return loadPayments();if(name==='users')return loadUsers();if(name==='audit')return loadAudit()}
async function loadDashboard(){const d=await api('/admin/dashboard');const c=d.counts;$('#stats').innerHTML=[['Pending farmers',c.farmers.pending],['Pending buyers',c.buyers.pending],['Open orders',c.open_orders],['Processed records',c.completed]].map(([a,b])=>`<article class="stat"><strong>${b}</strong><span>${a}</span></article>`).join('');$('#latest').innerHTML=d.latest.length?d.latest.map(x=>`<div class="list-item"><div><strong>${nameOf(x)}</strong><div class="ref">${x.reference}</div></div><span>${labelOf(x.type)}</span><span class="status ${statusClass(x.status)}">${x.status}</span><button onclick="openRecord('${plural(x.type)}',${x.id})">Review</button></div>`).join(''):`<div class="empty">No submissions yet.</div>`}
const plural=t=>t==='membership'?'memberships':t+'s';
const labelOf=t=>({farmer:'Farmer',buyer:'Buyer',order:'Order',membership:'Membership'})[t]||t;
const nameOf=r=>r.farm_name||r.business_name||r.payer_name||r.full_name||'Record';
const statusClass=s=>String(s).replaceAll(' ','-');
const configs={
 farmers:{title:'Farmer applications',desc:'Verify supplier identity, capacity, location and delivery capability.',cols:['Supplier','Location','Weekly capacity','Status','Assigned',''],row:r=>[`${r.farm_name}<div class="ref">${r.reference}</div>`,r.location,`${r.weekly_capacity} trays`,badge(r.status),r.assigned_to?.full_name||'Unassigned',`<div class="row-actions"><button onclick="openRecord('farmers',${r.id})">Review</button></div>`]},
 buyers:{title:'Business buyer registrations',desc:'Review commercial requirements and customer demand.',cols:['Buyer','Category','Weekly demand','Status','Assigned',''],row:r=>[`${r.business_name}<div class="ref">${r.reference}</div>`,r.category,r.weekly_volume,badge(r.status),r.assigned_to?.full_name||'Unassigned',`<div class="row-actions"><button onclick="openRecord('buyers',${r.id})">Review</button></div>`]},
 orders:{title:'Bulk order requests',desc:'Confirm supply, quotations and fulfilment ownership.',cols:['Customer','Quantity','Required date','Status','Quoted',''],row:r=>[`${r.business_name}<div class="ref">${r.reference}</div>`,r.quantity,new Date(r.required_date).toLocaleDateString('en-ZA'),badge(r.status),r.quoted_amount?`R${Number(r.quoted_amount).toFixed(2)}`:'Not quoted',`<div class="row-actions"><button onclick="openRecord('orders',${r.id})">Manage</button></div>`]},
 memberships:{title:'Membership and marketing applications',desc:'Review optional premium and campaign services.',cols:['Applicant','Service','Location','Status','Assigned',''],row:r=>[`${r.business_name}<div class="ref">${r.reference}</div>`,r.selected_service,r.location,badge(r.status),r.assigned_to?.full_name||'Unassigned',`<div class="row-actions"><button onclick="openRecord('memberships',${r.id})">Review</button></div>`]}
};
function badge(s){return `<span class="status ${statusClass(s)}">${s}</span>`}
async function loadResource(resource){const v=$('#'+resource),cfg=configs[resource];v.innerHTML=`<div class="page-head"><div><span class="eyebrow">Central records</span><h2>${cfg.title}</h2><p>${cfg.desc}</p></div><div class="toolbar"><input id="${resource}Search" placeholder="Search records"><select id="${resource}Status"><option value="all">All statuses</option><option>Pending</option><option>Approved</option><option>In progress</option><option>Completed</option><option>Rejected</option></select></div></div><div class="panel"><div id="${resource}Table"></div></div>`;const render=async()=>{const q=$('#'+resource+'Search').value,status=$('#'+resource+'Status').value;const d=await api(`/admin/${resource}?q=${encodeURIComponent(q)}&status=${encodeURIComponent(status)}`);$('#'+resource+'Table').innerHTML=d.items.length?`<table class="table"><thead><tr>${cfg.cols.map(c=>`<th>${c}</th>`).join('')}</tr></thead><tbody>${d.items.map(r=>`<tr>${cfg.row(r).map(c=>`<td>${c}</td>`).join('')}</tr>`).join('')}</tbody></table>`:`<div class="empty">No matching records.</div>`};$('#'+resource+'Search').oninput=debounce(render,250);$('#'+resource+'Status').onchange=render;await render()}
function debounce(fn,ms){let t;return()=>{clearTimeout(t);t=setTimeout(fn,ms)}}
window.openRecord=async(resource,id)=>{const [r,users]=await Promise.all([api(`/admin/${resource}/${id}`),api('/admin/users')]);const excluded=['id','assigned_to_id','internal_notes','created_at','updated_at','assigned_to'];const fields=Object.entries(r).filter(([k])=>!excluded.includes(k));$('#drawerBody').innerHTML=`<span class="eyebrow">${resource.slice(0,-1)} record</span><h2>${nameOf(r)}</h2><p class="ref">${r.reference}</p><div class="detail-grid">${fields.map(([k,v])=>`<div class="detail"><span>${k.replaceAll('_',' ')}</span><strong>${v??'—'}</strong></div>`).join('')}</div><form id="recordForm"><label>Status<select id="recordStatus">${['Pending','Approved','In progress','Completed','Rejected','Cancelled'].map(s=>`<option ${r.status===s?'selected':''}>${s}</option>`).join('')}</select></label><label>Assigned administrator<select id="recordOwner"><option value="">Unassigned</option>${users.filter(u=>u.is_active).map(u=>`<option value="${u.id}" ${r.assigned_to_id===u.id?'selected':''}>${u.full_name}</option>`).join('')}</select></label>${resource==='orders'?`<label>Quoted amount (R)<input id="quotedAmount" type="number" step="0.01" min="0" value="${r.quoted_amount||''}"></label>`:''}<label>Internal notes<textarea id="internalNotes" rows="5">${r.internal_notes||''}</textarea></label><button class="primary">Save changes</button></form>`;openDrawer();$('#recordForm').onsubmit=async e=>{e.preventDefault();const payload={status:$('#recordStatus').value,assigned_to_id:$('#recordOwner').value?Number($('#recordOwner').value):null,internal_notes:$('#internalNotes').value};if(resource==='orders')payload.quoted_amount=$('#quotedAmount').value?Number($('#quotedAmount').value):null;await api(`/admin/${resource}/${id}`,{method:'PATCH',body:JSON.stringify(payload)});toast('Record updated');closeDrawer();loadResource(resource)}};
function openDrawer(){$('#drawer').classList.remove('hidden');$('#drawerBackdrop').classList.remove('hidden')}function closeDrawer(){$('#drawer').classList.add('hidden');$('#drawerBackdrop').classList.add('hidden')}$('#closeDrawer').onclick=closeDrawer;$('#drawerBackdrop').onclick=closeDrawer;
async function loadUsers(){if(currentUser.role!=='CEO')return;const users=await api('/admin/users');$('#users').innerHTML=`<div class="page-head"><div><span class="eyebrow">Access governance</span><h2>Administrator management</h2><p>Add, suspend or remove administrators. The CEO account remains protected.</p></div><button class="primary" style="width:auto" onclick="openUserModal()">Add administrator</button></div><div class="panel"><table class="table"><thead><tr><th>Administrator</th><th>Role</th><th>Status</th><th>Last login</th><th></th></tr></thead><tbody>${users.map(u=>`<tr><td><strong>${u.full_name}</strong><div class="ref">${u.email}</div></td><td>${u.job_title}</td><td>${badge(u.is_active?'Approved':'Rejected')}</td><td>${u.last_login_at?new Date(u.last_login_at).toLocaleString('en-ZA'):'Never'}</td><td>${u.role==='CEO'?'<span class="ref">Protected owner</span>':`<button onclick="toggleUser(${u.id},${!u.is_active})">${u.is_active?'Suspend':'Activate'}</button> <button class="danger" onclick="removeUser(${u.id})">Remove</button>`}</td></tr>`).join('')}</tbody></table></div>`}
window.openUserModal=()=>{$('#modalBody').innerHTML=`<span class="eyebrow">Controlled access</span><h2>Add administrator</h2><form id="userForm"><label>Full name<input id="uName" required></label><label>Email<input id="uEmail" type="email" required></label><label>Job title<input id="uTitle" required></label><label>Temporary password<input id="uPass" type="password" minlength="10" required></label><button class="primary">Create administrator</button></form>`;openModal();$('#userForm').onsubmit=async e=>{e.preventDefault();await api('/admin/users',{method:'POST',body:JSON.stringify({full_name:$('#uName').value,email:$('#uEmail').value,job_title:$('#uTitle').value,temporary_password:$('#uPass').value})});toast('Administrator created');closeModal();loadUsers()}};
window.toggleUser=async(id,active)=>{await api(`/admin/users/${id}/status?active=${active}`,{method:'PATCH'});toast('Administrator status updated');loadUsers()};window.removeUser=async id=>{if(!confirm('Permanently remove this administrator?'))return;await api(`/admin/users/${id}`,{method:'DELETE'});toast('Administrator removed');loadUsers()};
function openModal(){$('#modal').classList.remove('hidden');$('#modalBackdrop').classList.remove('hidden')}function closeModal(){$('#modal').classList.add('hidden');$('#modalBackdrop').classList.add('hidden')}$('#closeModal').onclick=closeModal;$('#modalBackdrop').onclick=closeModal;
async function loadAudit(){const rows=await api('/admin/audit?limit=300');$('#audit').innerHTML=`<div class="page-head"><div><span class="eyebrow">Governance</span><h2>Audit trail</h2><p>Chronological record of access and operational decisions.</p></div></div><div class="panel">${rows.length?`<table class="table"><thead><tr><th>Date</th><th>Actor</th><th>Action</th><th>Entity</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${new Date(r.created_at).toLocaleString('en-ZA')}</td><td>${r.actor_name}</td><td>${r.action}</td><td>${r.entity_type}${r.entity_id?' #'+r.entity_id:''}</td></tr>`).join('')}</tbody></table>`:'<div class="empty">No activity yet.</div>'}</div>`}
async function loadPayments(){const rows=await api('/admin/payments');$('#payments').innerHTML=`<div class="page-head"><div><span class="eyebrow">Finance control</span><h2>Payments</h2><p>Record invoices, EFT confirmations and payment status.</p></div><button class="primary" style="width:auto" onclick="openPaymentModal()">Add payment record</button></div><div class="panel">${rows.length?`<table class="table"><thead><tr><th>Reference</th><th>Payer</th><th>Amount</th><th>Method</th><th>Status</th><th>Date</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${r.reference}</td><td>${r.payer_name}</td><td>R${Number(r.amount).toFixed(2)}</td><td>${r.method}</td><td>${badge(r.status)}</td><td>${new Date(r.created_at).toLocaleDateString('en-ZA')}</td></tr>`).join('')}</tbody></table>`:'<div class="empty">No payment records yet.</div>'}</div>`}
window.openPaymentModal=()=>{$('#modalBody').innerHTML=`<span class="eyebrow">Finance record</span><h2>Add payment</h2><form id="payForm"><label>Related to<select id="pType"><option value="order">Order</option><option value="membership">Membership</option></select></label><label>Record ID<input id="pEntity" type="number" min="1" required></label><label>Payer name<input id="pName" required></label><label>Amount (R)<input id="pAmount" type="number" step="0.01" min="0.01" required></label><label>Method<select id="pMethod"><option>EFT / bank transfer</option><option>PayShap</option><option>Card</option><option>Cash deposit</option></select></label><label>Status<select id="pStatus"><option>Pending</option><option>Invoiced</option><option>Part paid</option><option>Paid</option><option>Failed</option><option>Refunded</option></select></label><button class="primary">Save payment</button></form>`;openModal();$('#payForm').onsubmit=async e=>{e.preventDefault();await api('/admin/payments',{method:'POST',body:JSON.stringify({entity_type:$('#pType').value,entity_id:Number($('#pEntity').value),payer_name:$('#pName').value,amount:Number($('#pAmount').value),method:$('#pMethod').value,status:$('#pStatus').value})});toast('Payment record created');closeModal();loadPayments()}};
if(token)start();
